### ISSUE TITLE
Reorganize workers to contain some data from each layer

### ISSUE THREAD

**Issue by orangejulius** [pelias/wof-admin-lookup#116]
We have been running into build failures recently because the child processes for our admin lookup are running out of memory. A key cause of that is the way data is stored. Each admin lookup worker stores all the data from a single layer. Some layers are small, but some are very large, and those are the first to run out of memory.

I propose we reorganize the admin lookup code, so that some data from each layer is contained within each worker (and the number of workers is configurable, rather than forced to match with the number of layers). Each worker would internally keep data from each layer separate, so that queries for single layers would still work.

In paper diagram form:
![20170609_155830](https://user-images.githubusercontent.com/111716/26992707-de81a708-4d2d-11e7-88c5-bbc28ec070f2.jpg)
![20170609_155839](https://user-images.githubusercontent.com/111716/26992708-de84ec10-4d2d-11e7-8128-8b66ad2267cf.jpg)
![20170609_155848](https://user-images.githubusercontent.com/111716/26992709-de865cb2-4d2d-11e7-86b6-a9c5d53943ee.jpg)
![20170609_155856](https://user-images.githubusercontent.com/111716/26992710-de875bbc-4d2d-11e7-860b-0dc3fe7c57a2.jpg)
![20170609_155904](https://user-images.githubusercontent.com/111716/26992740-f99f22ae-4d2d-11e7-8210-dd4e9cbcca41.jpg)

**Comment by dianashk** [comment]
@orangejulius These are some sweet paper diagrams! 📄 ✨

**Comment by orangejulius** [comment]
I think we've settled that we are not going to improve the architecture of the pip service at this point. The [spatial service](https://github.com/pelias/spatial) will take over instead.
