### ISSUE TITLE
New Admin Lookup strategy has surfaced many WOF records with incorrect hiearchies

### ISSUE THREAD

**Issue by orangejulius** [pelias/wof-admin-lookup#156]
After https://github.com/pelias/wof-admin-lookup/pull/143 we now have an awesome and much faster way of doing admin lookup. However, it relies more on the hierarchies of individual records, rather than doing point-in-polygon across all layers itself and effectively bypassing the WOF hierarchy. As a result many records that possibly never had correct hierarchies are now causing problems.

### Erbil, Iraq
http://pelias.github.io/compare/#/v1/search%3Ftext=Erbil,%20Iraq
![image](https://user-images.githubusercontent.com/111716/30936799-ec642442-a3a2-11e7-941b-8c8bfb685e3a.png)
https://whosonfirst.mapzen.com/spelunker/id/421200817/
![image](https://user-images.githubusercontent.com/111716/30936819-015d6962-a3a3-11e7-8caa-74524345d1ab.png)

### Bourail, New CAledonia
http://pelias.github.io/compare/#/v1/search%3Ftext=Bourail
![image](https://user-images.githubusercontent.com/111716/30989837-25acc996-a46d-11e7-8ed2-5709f2947040.png)
https://whosonfirst.mapzen.com/spelunker/id/890438255/

**Comment by missinglink** [comment]
I have recently noticed that many hierarchies which were previously in the data are no longer there.

related: https://github.com/whosonfirst-data/whosonfirst-data/issues/954

**Comment by orangejulius** [comment]
Both of these cases have been fixed with WOF updates over the years. While we'll never get every hierarchy correct, we're well past the point of considering this a serious issue overall. If we do find more problematic hierarchies, we can handle them with individual issues here or in the whosonfirst repos
