### ISSUE TITLE
Support PIP via HTTP to the PIP Service

### ISSUE THREAD

**Issue by orangejulius** [pelias/wof-admin-lookup#160]
Loading all of WOF into memory for every importer is not ideal, and very time consuming. While it might be slightly higher latency to do PIP calls over HTTP, the overall throughput of talking to the PIP service should be similar, which is all that matters for imports. The savings in memory usage would allow us to scale up importing as well, and might help imports be faster overall.

Connects https://github.com/pelias/openstreetmap/issues/345

**Comment by tadjik1** [comment]
@orangejulius please take a look at #162. it should resolve this issue
