### ISSUE TITLE
Use a higher timeout for remote PIP resolver

### ISSUE THREAD

**Issue by otbutz** [pelias/wof-admin-lookup#192]
The remote PIP resolver uses the [microservice-wrapper](https://github.com/pelias/microservice-wrapper#usage) with its default config: 250ms timeout, 3 retries

This leads to possible errors during the import if the PIP service is hit with a high amount of queries:

```
2018-03-09T13:33:42.000Z - error: [pip] http://localhost:3102/9.170422/42.445732?layers=neighbourhood,borough,locality,localadmin,county,macrocounty,region,macroregion,dependency,country: {"timeout":250,"code":"ECONNABORTED","errno":"ETIME","retries":3}
```

The default timeout value should be raised and made configurable through `pelias.json`.

**Comment by orangejulius** [comment]
We should definitely raise the default timeout. That would be a PR to [microservice-wrapper](https://github.com/pelias/microservice-wrapper) [here](https://github.com/pelias/microservice-wrapper/blob/master/ServiceConfiguration.js#L17).

It is already configurable with a section like this in `pelias.json`
```
  "api": {
    "services": {
      "pip": {
        "url": "http://localhost:3102",
        "timeout": 5000
      }   
    }   
  }
```
