### ISSUE TITLE
how is wof-admin-lookup used in the docker setup.

### ISSUE THREAD

**Issue by mohammedayub44** [pelias/wof-admin-lookup#265]
Hi,

While I was doing the docker setup (for any of the areas). When I do a 
`pelias compose pull` I don't see this in the pulled image list. 

![pelais_compose_pull_allimages](https://user-images.githubusercontent.com/7122670/59514537-0d861480-8e8b-11e9-8f80-ea383332d950.PNG)

So my question is, 
Does is have its own image ? 
Is this service used at any point while querying (I know its primary built of reverse geo-coding), I'm slightly confused how is it being actually called from the existing pulled images.
@missinglink  @orangejulius 

Thanks !

**Comment by orangejulius** [comment]
First, please don't make a habit of mentioning myself and missinglink in every single issue. We see them all and respond when we can.

This project produces an [NPM package](https://www.npmjs.com/package/pelias-wof-admin-lookup) that is used by each of the importers and the pip-service. It does not have its own Docker image.

**Comment by mohammedayub44** [comment]
Sorry about that, will see to that in my future issues. 

Thanks for the immediate help !
