### ISSUE TITLE
Geonames records have extra, duplicate, label components

### ISSUE THREAD

**Issue by orangejulius** [pelias/wof-admin-lookup#49]
Our current admin layer lookup [mapping](https://github.com/pelias/wof-admin-lookup/blob/master/src/getAdminLayers.js) tells admin layers to be looked up in all admin layers above that of the record, but also including that of the layers themselves. So, for example, locality records from Geonames will be annotated with a locality record from Who's on First.

It used to be that our label generating system required this. However, now it's actually detrimental: when the name from Geonames does not exactly match the name from WOF, the label contains duplicate sections. Here are some examples:

[People's Republic of China, China](http://pelias.github.io/compare/#/v1/search%3Fsources=gn&size=1&text=china)
[City of Detroit, Detroit, MI](http://pelias.github.io/compare/#/v1/search%3Fsources=gn&size=2&text=detroit,%20mi)
[New York City, New York, NY, USA](http://pelias.github.io/compare/#/v1/search%3Fsources=gn&layers=locality&size=1&text=city%20of%20new%20york)

We also appear to not handle localadmin level records very well, because they aren't explicitly configured in the layer mapping. So, for example:

[City of New York, Brooklyn, New York, NY USA](http://pelias.github.io/compare/#/v1/search%3Fsources=gn&size=1&text=city%20of%20new%20york)

**Comment by dianashk** [comment]
Do we have corresponding acceptance tests for this issue?

**Comment by orangejulius** [comment]
Good idea, we should add some. Fixing https://github.com/pelias/api/issues/569 would help creating those acceptance tests though

**Comment by trescube** [comment]
This is no longer an issue of admin-lookup, but of geonames.

**Comment by orangejulius** [comment]
We do have acceptance-tests, pelias/acceptance-tests#259 covers these cases

**Comment by dianashk** [comment]
All fixed except China.

**Comment by trescube** [comment]
Potential solution: check label generation to see if country can be special-cased to just use name
